export const mockData = {
    headers: [{ name: "Log ID", sortBy: "", keyName: "logId" },
    { name: "Application Type", sortBy: "", keyName: "applicationType" },
    { name: "Application ID", sortBy: "", keyName: "applicationId" },
    { name: "Action", sortBy: "", keyName: "actionType" },
    { name: "Action Details", sortBy: "", keyName: "" },
    { name: "Date : Time", sortBy: "", keyName: "creationTimestamp" }],
    tableData: [{ actionType: "DARI_REFRESH_TOKEN", applicationId: null, applicationType: null, companyId: null, creationTimestamp: "2022-01-31 17:29:00", ip: "10.11.0.89", logId: 906468196730134, logInfo: null, ownerId: null, source: null, userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36", userId: 115678 }],
    allData: [],
    number: 0,
    recordsFiltered: 0,
    recordsTotal: 0,
    totalPages: 0,
    currentPage: 1,
    pageSize: 10,
    employername: "",
    actionType: "",
    applicationType: "",
    fromDate: "",
    toDate: "",
    applicationId: "",
    actionTypes: [],
    applicationTypes: []
};