export const initialState = {
    headers: ["Log ID",
        "Application Type",
        "Application ID",
        "Action",
        "Action Details",
        "Date : Time"],
    tableData: [],
    allData: [],
    number: 0,
    recordsFiltered: 0,
    recordsTotal: 0,
    totalPages: 0,
    currentPage: 1,
    pageSize: 10,
    employername: "",
    actionType: "",
    applicationType: "",
    fromDate: "",
    toDate: "",
    applicationId: "",
    actionTypes: [],
    applicationTypes: []
}